[default]

# NOME DO MODELO
APPNAME = 'DASHBOARD_COVID'

# DIRETÓRIO DE SAVE DOS LOGS
DIR_SAVE_LOGS = 'LOGS'

# ARQUIVO DE SAVE DOS LOGS - LOGGING
LOG_FILENAME = 'LOG_DASHBOARD_COVID.log'

# LEVEL DE CRITICIDADE DO LOG A SER REGISTRADO
LOGLEVEL = 'DEBUG'
LOGLEVEL_FILE = 'DEBUG'
LOGLEVEL_CONSOLE = 'DEBUG'

FORMAT_TYPES_ACCEPTED = ["jpg", "png"]

# INICIANDO A VARIÁVEL DE LOGGERS
LOGGERS = {}

[development]

# DIRETÓRIO CONTENDO DADOS DO BRASIL E ESTADOS - COVID
DIR_DATA = "DATA"
NAME_DATA_BRAZIL = "HIST_PAINEL_COVIDBR_BRAZIL_COUNTRY.csv"
NAME_DATA_STATES = "HIST_PAINEL_COVIDBR_BRAZIL_STATES.csv"